CREATE SEQUENCE TBL_POST;


CREATE TABLE TBL_POST(
   ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
   POST_ID VARCHAR2(255) NOT NULL,
   POST_CONTENT VARCHAR2(255) NOT NULL,
   MEMBER_ID VARCHAR2(255) NOT NULL,
   CREATE_DATE DATE DEFAULT SYSDATE,
   UPDATED_DATE DATE DEFAULT SYSDATE
   
);
SELECT * FROM TBL_POST;