/*
    1. 요구사항 분석
        안녕하세요 중고차 딜러입니다.
        이번에 자동차와 차주를 관리하고자 방문했습니다.
        자동차는 여러 명의 차주로 히스토리에 남아야 하고,
        차주는 여러 대의 자동차를 소유할 수 있습니다.
        그래서 우리는 항상 등록증(Registration)을 작성합니다.
        자동차는 브랜드, 모델명, 가격, 출시날짜가 필요하고
        차주는 이름, 전화번호, 주소가 필요합니다.

    2. 개념 모델링
    3. 논리 모델링
    4. 물리 모델링
    5. 구현
*/

CREATE TABLE TBL_CAR(
	ID NUMBER CONSTRAINT PK_CAR PRIMARY KEY,
	CAR_BRAND VARCHAR2(255) NOT NULL,
	CAR_NAME VARCHAR2(255) NOT NULL,
	CAR_PRICE NUMBER DEFAULT 1,
	CAR_RELEASE_DATE DATE
);
	
CREATE TABLE TBL_OWNER(
	ID NUMBER CONSTRAINT PK_OWNER PRIMARY KEY,
	OWNER_NAME VARCHAR2(255) NOT NULL,
	OWNER_PHONE VARCHAR2(255) NOT NULL,
	OWNER_ADDRESS VARCHAR2(255) NOT NULL
);

CREATE TABLE TBL_REGISTRATION(
	ID NUMBER CONSTRAINT PK_REGISTRATION PRIMARY KEY,
	CAR_ID NUMBER NOT NULL,
	OWNER_ID NUMBER NOT NULL,
	CONSTRAINT FK_CAR_INPORMATION FOREIGN KEY(CAR_ID)
	REFERENCES TBL_CAR(ID),
	CONSTRAINT FK_OWNER_INPORMATION FOREIGN KEY(OWNER_ID)
	REFERENCES TBL_OWNER(ID)
);


CREATE TABLE TBL_CAR(
   ID NUMBER CONSTRAINT PK_CAR PRIMARY KEY,
   CAR_BRAND VARCHAR2(255) NOT NULL,
   CAR_NAME VARCHAR2(255) NOT NULL,
   CAR_PRICE NUMBER DEFAULT 0,
   CAR_RELEASE_DATE DATE
);

CREATE TABLE TBL_OWNER(
   ID NUMBER CONSTRAINT PK_OWNER PRIMARY KEY,
   OWNER_ID VARCHAR2(255) CONSTRAINT UK_OWNER UNIQUE NOT NULL,
   OWNER_PASSWORD VARCHAR2(255) NOT NULL,
   OWNER_NAME VARCHAR2(255) NOT NULL,
   OWNER_ADDRESS VARCHAR2(255) NOT NULL,
   OWNER_EMAIL VARCHAR2(255),
   OWNER_BIRTH DATE
);

CREATE TABLE TBL_REGISTRATION(
   ID NUMBER CONSTRAINT PK_REGISTRATION PRIMARY KEY,
   OWNER_ID NUMBER,
   CAR_ID NUMBER,
   CONSTRAINT FK_REGISTRATION_OWNER FOREIGN KEY(OWNER_ID)
   REFERENCES TBL_OWNER(ID),
   CONSTRAINT FK_REGISTRATION_CAR FOREIGN KEY(CAR_ID)
   REFERENCES TBL_CAR(ID)
);

