/*
 * 요구 사항
 * 
 * 회의실 예약 서비스를 제작하고 싶습니다.
 * 회원별로 등급이 존재하고 사무실마다 회의실이 여러 개 있습니다.
 * 회의실 이용 가능 시간은 파트 타임으로서 여러 시간대가 존재합니다.
 * 
 * */

/*회원		사무실
 * 등급		회의실
 * */

CREATE TABLE TBL_MEMBER(
   ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
   MEMBER_ID VARCHAR2(255) CONSTRAINT UK_MEMBER UNIQUE NOT NULL,
   MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
   MEMBER_NAME VARCHAR2(255) NOT NULL,
   MEMBER_ADDRESS VARCHAR2(255) NOT NULL,
   MEMBER_EMAIL VARCHAR2(255),
   MEMBER_GARDE NUMBER DEFAULT 1
);

CREATE TABLE TBL_OFFICE(
	ID NUMBER CONSTRAINT PK_OFFICE PRIMARY KEY,
	OFFICE_ROOM NUMBER NOT NULL,
	MEMBER_ID NUMBER NOT NULL,
	CONSTRAINT FK_MEMBER_OFFICE FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);


CREATE TABLE TBL_MEETING_ROOM(
   ID NUMBER CONSTRAINT PK_MEETING_ROOM PRIMARY KEY,
   ROOM_NUMBER VARCHAR2(255) NOT NULL,
   CAPACITY NUMBER NOT NULL,
   AVAILABILITY VARCHAR2(255),
   OFFICE_ID NUMBER NOT NULL,
   CONSTRAINT FK_MEETING_ROOM_OFFICE FOREIGN KEY(OFFICE_ID)
   REFERENCES TBL_OFFICE(ID)
);

CREATE TABLE TBL_RESERVATION(
	ID NUMBER CONSTRAINT PK_RESERVATION PRIMARY KEY,
	MEETING_ROOM_ID NUMBER NOT NULL,
	MEMBER_ID NUMBER NOT NULL,
	CONSTRAINT FK_MEMBER_RESERVATION FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_MEETING_ROOM_RESERVATION FOREIGN KEY(MEETING_ROOM_ID)
	REFERENCES TBL_MEETING_ROOM(ID)
);

CREATE TABLE TBL_RESERVATION_START(
	ID NUMBER CONSTRAINT PK_RESERVATION_START PRIMARY KEY,
	START_TIME DATE NOT NULL,
	RESERVATION_ID NUMBER NOT NULL,
	CONSTRAINT FK_RESERVATION_START FOREIGN KEY(RESERVATION_ID)
	REFERENCES TBL_RESERVATION(ID)
);

CREATE TABLE TBL_RESERVATION_END(
	ID NUMBER CONSTRAINT PK_RESERVATION_END PRIMARY KEY,
	END_TIME DATE NOT NULL,
	RESERVATION_ID NUMBER NOT NULL,
	CONSTRAINT FK_RESERVATION_END FOREIGN KEY(RESERVATION_ID)
	REFERENCES TBL_RESERVATION(ID)
);


------------------------------------------------------------------------------------
CREATE TABLE TBL_MEMBER(
   ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
   MEMBER_ID VARCHAR2(255) CONSTRAINT UK_MEMBER UNIQUE NOT NULL,
   MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
   MEMBER_NAME VARCHAR2(255) NOT NULL,
   MEMBER_ADDRESS VARCHAR2(255) NOT NULL,
   MEMBER_EMAIL VARCHAR2(255),
   MEMBER_BIRTH DATE
);

CREATE TABLE TBL_OFFICE(
   ID NUMBER CONSTRAINT PK_OFFICE PRIMARY KEY,
   OFFICE_NAME VARCHAR2(255) NOT NULL,
   OFFICE_LOCATION VARCHAR2(255) NOT NULL
);

CREATE TABLE TBL_CONFERENCE_ROOM(
   ID NUMBER CONSTRAINT PK_CONFERENCE_ROOM PRIMARY KEY,
   OFFICE_ID NUMBER NOT NULL,
   CONSTRAINT FK_CONFERENCE_ROOM_OFFICE FOREIGN KEY(OFFICE_ID)
   REFERENCES TBL_OFFICE(ID)
);

CREATE TABLE TBL_PART_TIME(
   ID NUMBER CONSTRAINT PK_PART_TIME PRIMARY KEY,
   START_TIME DATE NOT NULL,
   END_TIME DATE NOT NULL,
   CONFERENCE_ROOM_ID NUMBER NOT NULL,
   CONSTRAINT FK_PART_TIME_CONFERENCE_ROOM FOREIGN KEY(CONFERENCE_ROOM_ID)
   REFERENCES TBL_CONFERENCE_ROOM(ID)
);

CREATE TABLE TBL_RESERVATION(
   ID NUMBER CONSTRAINT PK_RESERVATION PRIMARY KEY,
   MEMBER_ID NUMBER NOT NULL,
   PART_TIME_ID NUMBER NOT NULL,
   CONSTRAINT FK_RESERVATION_MEMBER FOREIGN KEY(MEMBER_ID)
   REFERENCES TBL_MEMBER(ID),
   CONSTRAINT FK_RESERVATION_PART_TIME FOREIGN KEY(PART_TIME_ID)
   REFERENCES TBL_PART_TIME(ID)
);
