CREATE TABLE TBL_PARENTS(
	ID NUMBER CONSTRAINT PK_PARENTS PRIMARY KEY,
	PARENTS_NAME VARCHAR2(255) NOT NULL,
	PARENTS_AGE NUMBER NOT NULL,
	PARENTS_PHONE VARCHAR2(255) NOT NULL,
	PARENTS_ADDRESS VARCHAR2(255) NOT NULL,
	PARENTS_GENDER NUMBER DEFAULT 3
);

CREATE TABLE TBL_KID(
    ID NUMBER CONSTRAINT PK_KID PRIMARY KEY,
    KID_NAME VARCHAR2(255) NOT NULL,
    KID_AGE NUMBER NOT NULL,
    KID_GENDER NUMBER DEFAULT 3,
    PARENTS_ID NUMBER NOT NULL,
    CONSTRAINT FK_PARENTS_KID FOREIGN KEY(PARENTS_ID)
 	REFERENCES TBL_PARENTS(ID)
);

CREATE TABLE TBL_WORK_STUDY(
	ID NUMBER CONSTRAINT PK_WORK_STUDY PRIMARY KEY,
	WORK_STUDY_TITLE VARCHAR2(255) CONSTRAINT UK_WORK_STUDY UNIQUE NOT NULL,
	WORK_STUDY_CONTENT VARCHAR2(255) NOT NULL,
	WORK_STUDY_IMAGE VARCHAR2(255) NOT NULL,
	KID_ID NUMBER NOT NULL
);

CREATE TABLE TBL_REGISTRATION(
	ID NUMBER CONSTRAINT PK_REGISTRATION PRIMARY KEY,
	KID_ID NUMBER NOT NULL,
	WORK_STUDY_ID NUMBER NOT NULL,
	PARENTS_ID NUMBER NOT NULL,
	CONSTRAINT FK_KID_WORK_STUDY FOREIGN KEY(KID_ID)
 	REFERENCES TBL_KID(ID),
 	CONSTRAINT FK_WORK_STUDY_WORK_STUDY FOREIGN KEY(WORK_STUDY_ID)
 	REFERENCES TBL_WORK_STUDY(ID)
);

--------------------------------------------------------------------------------
CREATE TABLE TBL_KINDERGARTEN(
   ID NUMBER CONSTRAINT PK_KINDERGARTEN PRIMARY KEY,
   KINDERGARTEN_NAME VARCHAR2(255),
   KINDERGARTEN_ADDRESS VARCHAR2(255)
);

CREATE TABLE TBL_PARENT(
   ID NUMBER CONSTRAINT PK_PARENT PRIMARY KEY,
   PARENT_NAME VARCHAR2(255) NOT NULL,
   PARENT_ADDRESS VARCHAR2(255) NOT NULL,
   PARENT_PHONE VARCHAR2(255) NOT NULL,
   PARENT_GENDER NUMBER DEFAULT 3
);

CREATE TABLE TBL_CHILD(
   ID NUMBER CONSTRAINT PK_CHILD PRIMARY KEY,
   CHILD_AGE NUMBER NOT NULL,
   CHILD_GENDER NUMBER DEFAULT 3,
   PARENT_ID NUMBER,
   CONSTRAINT FK_CHILD_PARENT FOREIGN KEY(PARENT_ID)
   REFERENCES TBL_PARENT(ID)
);

CREATE TABLE TBL_FIELD_TRIP(
   ID NUMBER CONSTRAINT PK_FIELD_TRIP PRIMARY KEY,
   FIELD_TRIP_TITLE VARCHAR2(255),
   FIELD_TRIP_CONTENT VARCHAR2(255),
   KINDERGARTEN_ID NUMBER,
   CONSTRAINT FK_FIELD_TRIP_KINDERGARTEN FOREIGN KEY(KINDERGARTEN_ID)
   REFERENCES TBL_KINDERGARTEN(ID)
);

CREATE TABLE TBL_FILE(
   ID NUMBER CONSTRAINT PK_FILE PRIMARY KEY,
   FILE_NAME VARCHAR2(255),
   FILE_PATH VARCHAR2(255),
   FILE_SIZE NUMBER
);

CREATE TABLE TBL_FIELD_TRIP_FILE(
   ID NUMBER CONSTRAINT PK_FIELD_DRIP_FILE PRIMARY KEY,
   FIELD_TRIP_ID NUMBER NOT NULL,
   CONSTRAINT FK_FIELD_TRIP_FILE_FIELD_TRIP FOREIGN KEY(FIELD_TRIP_ID)
   REFERENCES TBL_FIELD_TRIP(ID),
   CONSTRAINT FK_FIELD_TRIP_FILE_FILE FOREIGN KEY(ID)
   REFERENCES TBL_FILE(ID)
);

CREATE TABLE TBL_MEMBER(
   ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
   MEMBER_ID VARCHAR2(255) CONSTRAINT UK_MEMBER UNIQUE NOT NULL,
   MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
   MEMBER_NAME VARCHAR2(255) NOT NULL,
   MEMBER_ADDRESS VARCHAR2(255) NOT NULL,
   MEMBER_EMAIL VARCHAR2(255),
   MEMBER_BIRTH DATE,
   KINDERGARTEN_ID NUMBER,
   CONSTRAINT FK_MEMBER_KINDERGARTEN FOREIGN KEY(KINDERGARTEN_ID)
   REFERENCES TBL_KINDERGARTEN(ID)
);