CREATE TABLE TBL_BOOK (
    ID NUMBER CONSTRAINT PK_BOOK PRIMARY KEY,
    BOOK_TITLE VARCHAR2(255) NOT NULL,
    BOOK_AUTHOR VARCHAR2(255) NOT NULL,
    BOOK_PUBLISHER VARCHAR2(255),
    BOOK_ISBN VARCHAR2(20) UNIQUE,
    BOOK_PUBLISH_DATE DATE
);

CREATE TABLE TBL_MEMBER(
    ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
    MEMBER_NAME VARCHAR2(255) NOT NULL,
    MEMBER_PHONE VARCHAR2(20),
    MEMBER_ADDRESS VARCHAR2(255)
);

CREATE TABLE TBL_RENTAL (
    ID NUMBER CONSTRAINT PK_RENTAL PRIMARY KEY,
    RENTAL_DATE DATE NOT NULL,
    RETURN_DATE DATE,
    BOOK_ID NUMBER NOT NULL,
    MEMBER_ID NUMBER NOT NULL,
    CONSTRAINT FK_BOOK_RENTAL FOREIGN KEY(BOOK_ID)
	REFERENCES TBL_BOOK(ID),
	CONSTRAINT FK_MEMBER_RENTAL FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);

--------------------------------------------------------------------
CREATE TABLE TBL_PATIENT(
	ID NUMBER CONSTRAINT PK_PATIENT PRIMARY KEY,
	PATIENT_ID VARCHAR2(255) NOT NULL,
	PATIENT_AGE NUMBER DEFAULT 1,
	PATIENT_GENTER VARCHAR2(255) NOT NULL,
	PATIENT_ADDRESS VARCHAR2(255) NOT NULL
);

CREATE TABLE TBL_DOCTOR(
	ID NUMBER CONSTRAINT PK_DOCTOR PRIMARY KEY,
	DOCTOR_NAME VARCHAR2(255) NOT NULL,
	DOCTOR_MAJOR VARCHAR2(255) NOT NULL,
	DOCTOR_CONTACT VARCHAR2(255) NOT NULL
);

CREATE TABLE TBL_VISIT(
	ID NUMBER CONSTRAINT PK_VISIT PRIMARY KEY,
	VISIT_DATE DATE NOT NULL,
	PATIENT_ID NUMBER NOT NULL,
	DOCTOR_ID NUMBER NOT NULL,
	CONSTRAINT FK_PATIENT_VISIT FOREIGN KEY(PATIENT_ID)
	REFERENCES TBL_PATIENT(ID),
	CONSTRAINT FK_DOCTOR_VISIT FOREIGN KEY(DOCTOR_ID)
	REFERENCES TBL_DOCTOR(ID)
);

--------------------------------------------------------------------
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(255) CONSTRAINT UK_MEMBER UNIQUE NOT NULL,
	MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
	MEMBER_NAME VARCHAR2(255) NOT NULL,
	MEMBER_ADDRESS VARCHAR2(255) NOT NULL,
	MEMBER_EMAIL VARCHAR2(255),
	MEMBER_BIRTH DATE
);

CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL,
	PRODUCT_PRICE NUMBER NOT NULL,
	PRODUCT_STOCK NUMBER NOT NULL
);

CREATE TABLE TBL_ORDER(
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	ORDER_DATE DATE DEFAULT CURRENT_TIMESTAMP,
	MEMBER_ID NUMBER NOT NULL,
	CONSTRAINT FK_MEMBER_ORDER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);

CREATE TABLE TBL_ORDER_ITEM(
	ID NUMBER CONSTRAINT PK_ORDER_ITEM PRIMARY KEY,
	PRODUCT_ID NUMBER NOT NULL,
	ORDER_ID NUMBER NOT NULL,
	CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID),
	CONSTRAINT FK_ORDER_ORDER FOREIGN KEY(ORDER_ID)
	REFERENCES TBL_ORDER(ID)
);










